#!name=信息面板
#!desc=信息面板

[Script]
TrafficStatistics = type=generic,timeout=10,script-path= https://raw.githubusercontent.com/fishingworld/something/main/PanelScripts/trafficstatistics.js ,argument=icon=arrow.up.arrow.down.circle&color=#5d84f8
net-info-panel=type=generic,timeout=10,script-path=https://raw.githubusercontent.com/ventusyu/ventus/main/Panel/Net-info-panel.js
nf_check = type=generic,timeout=5,script-path=https://gist.githubusercontent.com/Hyseen/b06e911a41036ebc36acf04ddebe7b9a/raw/nf_check.js
ytb_check = type=generic,timeout=5,script-path=https://gist.githubusercontent.com/Hyseen/5ae36a6a5cb5690b1f2bff4aa19c766f/raw/youtube_premium_check.js

#机场信息
#必须修改的字段:你encode后的机场订阅链接
Sub_info = type=generic,timeout=10,script-path=https://raw.githubusercontent.com/mieqq/mieqq/master/sub_info_panel.js ,script-update-interval=0,argument=url=[URL encode 后的机场节点链接]&reset_day=1&title=NFCloud&icon=opticaldisc&color=#5AC8FA




[Panel]
TrafficStatistics = script-name=TrafficStatistics, title="流量统计", content="请刷新", update-interval=-1
net-info-panel=title="网络状态",content="请刷新",style=info,script-name=net-info-panel
nf_check = script-name=nf_check, title="Netflix 解锁检测", content="请刷新", update-interval=-1
ytb_check = script-name=ytb_check, title="YouTube Premium 解锁检测", update-interval=-1
#机场信息
Sub_info = script-name=Sub_info,update-interval = 86400

