#!name=信息面板
#!desc=信息面板

[Script]
TrafficStatistics = type=generic,timeout=10,script-path= https://raw.githubusercontent.com/fishingworld/something/main/PanelScripts/trafficstatistics.js ,argument=icon=arrow.up.arrow.down.circle&color=#5d84f8
net-info-panel=type=generic,timeout=10,script-path=https://raw.githubusercontent.com/ventusyu/ventus/main/Panel/Net-info-panel.js
nf_check = type=generic,timeout=5,script-path=https://gist.githubusercontent.com/Hyseen/b06e911a41036ebc36acf04ddebe7b9a/raw/nf_check.js
ytb_check = type=generic,timeout=5,script-path=https://gist.githubusercontent.com/Hyseen/5ae36a6a5cb5690b1f2bff4aa19c766f/raw/youtube_premium_check.js





[Panel]
TrafficStatistics = script-name=TrafficStatistics, title="流量统计", content="请刷新", update-interval=-1
net-info-panel=title="网络状态",content="请刷新",style=info,script-name=net-info-panel
nf_check = script-name=nf_check, title="Netflix 解锁检测", content="请刷新", update-interval=-1
ytb_check = script-name=ytb_check, title="YouTube Premium 解锁检测", update-interval=-1

